# Generated by Django 2.2 on 2021-03-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='收件方')),
                ('contact_person', models.CharField(blank=True, max_length=12, null=True, verbose_name='联系人')),
                ('telephone', models.CharField(max_length=13, unique=True, verbose_name='联系号码')),
                ('e_mail', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
            options={
                'verbose_name': '客户信息',
                'verbose_name_plural': '客户信息',
            },
        ),
        migrations.CreateModel(
            name='DeliveryDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='交货时间')),
            ],
            options={
                'verbose_name': '交货时间',
                'verbose_name_plural': '交货时间',
            },
        ),
        migrations.CreateModel(
            name='DeliveryMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='交货方式')),
            ],
            options={
                'verbose_name': '交货方式',
                'verbose_name_plural': '交货方式',
            },
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='产品名称')),
                ('remarks', models.CharField(blank=True, max_length=64, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '产品名称',
                'verbose_name_plural': '产品名称',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='付款方式')),
            ],
            options={
                'verbose_name': '付款方式',
                'verbose_name_plural': '付款方式',
            },
        ),
        migrations.CreateModel(
            name='ServicePolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='服务政策')),
            ],
            options={
                'verbose_name': '服务政策',
                'verbose_name_plural': '服务政策',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='单位')),
            ],
            options={
                'verbose_name': '单位',
                'verbose_name_plural': '单位',
            },
        ),
        migrations.CreateModel(
            name='ValidPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='有效期')),
            ],
            options={
                'verbose_name': '有效期',
                'verbose_name_plural': '有效期',
            },
        ),
        migrations.CreateModel(
            name='WarrantyPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='保修政策')),
            ],
            options={
                'verbose_name': '保修政策',
                'verbose_name_plural': '保修政策',
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('Qid', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True, verbose_name='订单编号')),
                ('date', models.DateField(auto_now=True, verbose_name='日期')),
                ('qty', models.FloatField(unique=True, verbose_name='数量')),
                ('price', models.FloatField(verbose_name='金额')),
                ('amount', models.FloatField(verbose_name='金额')),
                ('remarks', models.CharField(blank=True, max_length=128, null=True, verbose_name='备注')),
                ('client', models.ManyToManyField(related_name='client', to='app.Client', verbose_name='客户信息')),
                ('deliveryDate', models.ManyToManyField(to='app.DeliveryDate', verbose_name='交货时间')),
                ('deliveryMethod', models.ManyToManyField(to='app.DeliveryMethod', verbose_name='交货方式')),
                ('goods', models.ManyToManyField(related_name='goods', to='app.Goods', verbose_name='产品名称')),
                ('paymentTerms', models.ManyToManyField(to='app.PaymentTerms', verbose_name='付款方式')),
                ('servicePolicy', models.ManyToManyField(to='app.ServicePolicy', verbose_name='服务政策')),
                ('unit', models.ManyToManyField(related_name='unit', to='app.Unit', verbose_name='单位')),
                ('validPeriod', models.ManyToManyField(to='app.ValidPeriod', verbose_name='有效期')),
                ('warrantyPolicy', models.ManyToManyField(to='app.WarrantyPolicy', verbose_name='保修政策')),
            ],
            options={
                'verbose_name': '报价单',
                'verbose_name_plural': '报价单',
            },
        ),
        migrations.AddField(
            model_name='goods',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Unit', verbose_name='单位'),
        ),
    ]
