# Generated by Django 2.2 on 2021-03-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='client',
        ),
        migrations.AddField(
            model_name='quotation',
            name='client',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='client', to='app.Client', verbose_name='客户信息'),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='deliveryDate',
        ),
        migrations.AddField(
            model_name='quotation',
            name='deliveryDate',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.DeliveryDate', verbose_name='交货时间'),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='deliveryMethod',
        ),
        migrations.AddField(
            model_name='quotation',
            name='deliveryMethod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.DeliveryMethod', verbose_name='交货方式'),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='goods',
        ),
        migrations.AddField(
            model_name='quotation',
            name='goods',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='goods', to='app.Goods', verbose_name='产品名称'),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='paymentTerms',
        ),
        migrations.AddField(
            model_name='quotation',
            name='paymentTerms',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.PaymentTerms', verbose_name='付款方式'),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='servicePolicy',
        ),
        migrations.AddField(
            model_name='quotation',
            name='servicePolicy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.ServicePolicy', verbose_name='服务政策'),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='unit',
        ),
        migrations.AddField(
            model_name='quotation',
            name='unit',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='unit', to='app.Unit', verbose_name='单位'),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='validPeriod',
        ),
        migrations.AddField(
            model_name='quotation',
            name='validPeriod',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.ValidPeriod', verbose_name='有效期'),
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='warrantyPolicy',
        ),
        migrations.AddField(
            model_name='quotation',
            name='warrantyPolicy',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.WarrantyPolicy', verbose_name='保修政策'),
        ),
    ]
